[package]
name = "libuv-sys"
version = "0.1.0"
authors = ["Stefan O'Rear <stefanor@cox.net>"]
build = "build.rs"

[build-dependencies]
pkg-config = "0.3.6"

[dependencies]
libc = "0.1.10"

# [lib]
# crate-type = ["dylib"]
